### ISSUE TITLE
This project does not seem to compile... 

### ISSUE THREAD

**Issue by chrisribe** [chrisribe/firebase-titanium#1]
After forking from ianko/firebase-titanium and trying too compile this project I cannot seem to get it to run!
I keep getting this error:
ComLeftlanelabFirebaseModuleAssets.m:14:11: error: expected ';'
# 

`Mac-TiiLT:iphone cribe$ sudo python build.py 
[DEBUG] compiling: /Users/cribe/Documents/github-projects/firebase-titanium/iphone/../assets/com.leftlanelab.firebase.js
[DEBUG] detected symbol: App.Properties.getBool
[DEBUG] detected symbol: App.Properties.getString
Build settings from command line:
    SDKROOT = iphoneos9.3

=== BUILD TARGET Firebase iOS Module OF PROJECT Firebase iOS Module WITH CONFIGURATION Release ===

Check dependencies

CompileC build/Firebase\ iOS\ Module.build/Release-iphoneos/Firebase\ iOS\ Module.build/Objects-normal/arm64/ComLeftlanelabFirebaseModuleAssets.o Classes/ComLeftlanelabFirebaseModuleAssets.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/cribe/Documents/github-projects/firebase-titanium/iphone
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/sw/bin:/sw/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/X11R6/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch arm64 -fmessage-length=146 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=c99 -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wno-missing-braces -Wno-parentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wno-unused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -Wno-deprecated-implementations -DTI_VERSION= -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=6.0 -g -Wno-sign-conversion -iquote /Users/cribe/Documents/github-projects/firebase-titanium/iphone/build/Firebase\ iOS\ Module.build/Release-iphoneos/Firebase\ iOS\ Module.build/ComLeftlanelabFirebase-generated-files.hmap -I/Users/cribe/Documents/github-projects/firebase-titanium/iphone/build/Firebase\ iOS\ Module.build/Release-iphoneos/Firebase\ iOS\ Module.build/ComLeftlanelabFirebase-own-target-headers.hmap -I/Users/cribe/Documents/github-projects/firebase-titanium/iphone/build/Firebase\ iOS\ Module.build/Release-iphoneos/Firebase\ iOS\ Module.build/ComLeftlanelabFirebase-all-target-headers.hmap -iquote /Users/cribe/Documents/github-projects/firebase-titanium/iphone/build/Firebase\ iOS\ Module.build/Release-iphoneos/Firebase\ iOS\ Module.build/ComLeftlanelabFirebase-project-headers.hmap -I/Users/cribe/Documents/github-projects/firebase-titanium/iphone/build/Release-iphoneos/include -I/var/root/Library/Application\ Support/Titanium/mobilesdk/osx/5.1.1.GA/iphone/include -I/var/root/Library/Application\ Support/Titanium/mobilesdk/osx/5.1.1.GA/iphone/include/TiCore -I/var/root/Library/Application\ Support/Titanium/mobilesdk/osx/5.1.1.GA/iphone/include/JavaScriptCore -I/Users/cribe/Documents/github-projects/firebase-titanium/iphone/build/Firebase\ iOS\ Module.build/Release-iphoneos/Firebase\ iOS\ Module.build/DerivedSources/arm64 -I/Users/cribe/Documents/github-projects/firebase-titanium/iphone/build/Firebase\ iOS\ Module.build/Release-iphoneos/Firebase\ iOS\ Module.build/DerivedSources -F/Users/cribe/Documents/github-projects/firebase-titanium/iphone/build/Release-iphoneos -F/Users/cribe/Documents/github-projects/firebase-titanium/iphone/platform -DTI_POST_1_2 -include /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.DeveloperTools/7.3.1-7D1014/Xcode/SharedPrecompiledHeaders/ComLeftlanelabFirebase_Prefix-fcklzcfmcovrhwbhaakglcozcoxp/ComLeftlanelabFirebase_Prefix.pch -MMD -MT dependencies -MF /Users/cribe/Documents/github-projects/firebase-titanium/iphone/build/Firebase\ iOS\ Module.build/Release-iphoneos/Firebase\ iOS\ Module.build/Objects-normal/arm64/ComLeftlanelabFirebaseModuleAssets.d --serialize-diagnostics /Users/cribe/Documents/github-projects/firebase-titanium/iphone/build/Firebase\ iOS\ Module.build/Release-iphoneos/Firebase\ iOS\ Module.build/Objects-normal/arm64/ComLeftlanelabFirebaseModuleAssets.dia -c /Users/cribe/Documents/github-projects/firebase-titanium/iphone/Classes/ComLeftlanelabFirebaseModuleAssets.m -o /Users/cribe/Documents/github-projects/firebase-titanium/iphone/build/Firebase\ iOS\ Module.build/Release-iphoneos/Firebase\ iOS\ Module.build/Objects-normal/arm64/ComLeftlanelabFirebaseModuleAssets.o
/Users/cribe/Documents/github-projects/firebase-titanium/iphone/Classes/ComLeftlanelabFirebaseModuleAssets.m:14:11: error: expected ';' after
      expression
2016-06-06 11:49:58.342 titanium_prep[14016:2965700] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '...
          ^
          ;
/Users/cribe/Documents/github-projects/firebase-titanium/iphone/Classes/ComLeftlanelabFirebaseModuleAssets.m:14:14: error: expected ';' after
      expression
2016-06-06 11:49:58.342 titanium_prep[14016:2965700] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '...
             ^
             ;
`

**Comment by chrisribe** [comment]
Ok after upgrading to 5.3.0.GA I got it to compile (do not know if it's related..)
{will commit the recompiled version shortly}

**Steps to compile**
1. Import project in appcelerator studio
2. Changed titanium.xconfig SDK version to 5.3.0.GA (TITANIUM_SDK_VERSION and TITANIUM_SDK)
3. Run Package -> iOS AND change output location to a folder.

![screen shot 2016-06-06 at 2 26 34 pm](https://cloud.githubusercontent.com/assets/1999791/15833082/fd26321c-2bf2-11e6-80f5-c742e646a2fb.png)

Hope this helps...

**Update**
It seems it builds but does not run in an app... The Firebase.new is undefined.

**Comment by chrisribe** [comment]
Dam still open since 2016 ! 
Came back to the project and it's now using Jenkins... Any documentation on how to get started ?
